[package]
name = "AdventOfCode2022"
version = "0.1.0"
edition = "2021"
default-run = "day_01"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
